version: '3.1'
services:
  db:
    image: postgres
    container_name: example_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example_db
    ports:
      - "5444:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql